# Default initial positions for my_arm's ros2_control fake system

initial_positions:
  base_joint: 0
  elbow_bar_joint: -0.2
  elbow_roll_frame_joint: 0
  shoulder_bar_joint: 0.9
  wrist_pitch_bar_joint: -0.7
  wrist_roll_joint: 0
